# FROM docker:23.0.6-dind-alpine3.18
FROM docker:24.0.5-dind

USER root

COPY index.sh /index.sh

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install curl jq bash ca-certificates git openssh openssl unzip wget -y

WORKDIR /

ENTRYPOINT ["/index.sh"]